### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by zero2cx**
"All Rights Reserved" and "Open-Sourced via GPLv3" are two project release copyright statuses that directly conflict with one another. It's proper that a choice is made to either fully comply with the terms of the "GPLv3 copyright license" or, in the alternative, to close the project source code as proprietary and label it as "rights reserved." Thanks!

zero2cx <https://github.com/zero2cx>

### CODE REVIEW

**Comment by zero2cx** [comment]
Jamal, I opened this pull request because you should probably choose to repair your release license to be in full compliance with GPLv3. Abandoning GPL and closing the source would be another choice that is open to you, too. In either case, PacVim's "Copyright (c) 2015, Jamal Moon" shall be retained by you.

**Comment by jmoon018** [comment]
Hello zero2cx,

Thanks for the pull request. The license was supposed to be GPL, and the source code was not meant to be exclusively for me. However, I want to change the license from GPL to LGPL because I think GPL is a bit too restrictive. I believe that, in the cases of license changes, the owner (ie: me) has to make the changes, so I will do so shortly.

I will leave this thread open for a little bit in case you have any other concerns regarding the license. If you'd like to work on any other features in this repo, feel free to do so and I'll review it, but make a separate pull request.

Thanks,
Jamal

**Comment by zero2cx** [comment]
Cool! And you're welcome, Jamal.

If you are still at the decision-making stage, then the page at GNU may help you there:
[(https://www.gnu.org/licenses/why-not-lgpl.html)]
> The GNU Project has two principal licenses to use for libraries. One is the GNU Lesser GPL; the other is the ordinary GNU GPL. The choice of license makes a big difference: using the Lesser GPL permits use of the library in proprietary programs; using the ordinary GPL for a library makes it available only for free programs.

**Comment by zero2cx** [comment]
If you go the way of the GPLv3, the following header text should be pasted up top within every source file:
> This file is part of the PacVim software package.
> Copyright (C) 2015, 2016 Jamal Moon
> This program is free software; you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation; either version 3 of the License, or
> (at your option) any later version.
> This program is distributed in the hope that it will be useful,
> but WITHOUT ANY WARRANTY; without even the implied warranty of
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> GNU General Public License for more details.

**Comment by zero2cx** [comment]
Jamal, below is a somewhat enlightening quote from the page [located here](http://soundsoftware.ac.uk/open-source-software-licences-lgpl):
>Like the GPL, there are two widely used versions of the LGPL, LGPLv2.1 and LGPLv3. Unlike the GPL, LGPLv3 is shorter than v2.1 because it is written as an addendum to the GPL instead of as a self-contained licence.

If you do go the way of the LGPLv3 (or the LGPLv2.1, as I guess that version is favored by some devs or attorneys), then a different header text will be required atop each source file. I wasn't able to sort out the precise text for that, so I'll let you follow up with the detail of that. Keep in mind that I am a student and not any sort of expert, but I can do my best to advise or assist you in any way you'd wish. Thanks!

**Comment by jmoon018** [comment]
I've included the new license (COPYING, COPYING.LESSER), articulated the LGPL in README, and added the LGPL header to each of the source files. I believe that should be sufficient.

I'm going to close this pull request. If there any more concerns with the license, reopen this or make a new pull request.

Thanks

**Pull request closed without merging**
